version: '2'
services:
    api:
      build: './stackle_api'
      ports:
        - "8080:8080"
      links :
        - mongo
    mongo:
      image : mongo
    angular:
      build : './stackle_app'
      ports : 
        - "9000:9000"